Feature/3 header
al-ros/team-calendar pull request #10
Opened 2021-11-23 20:34 UTC by al-ros

![Screenshot_9](https://user-images.githubusercontent.com/83843811/143101711-66553258-5b67-4b36-bcf2-bd8bbbce509c.png)

create header+styles

2021-11-23 20:53 UTC, roman-vabishchevych requested changes

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Button/Button.jsx
> +    <button className={`button ${className}`} onClick={onClick}>{label}</button>
for managing classnames better to use 'classnames' library

https://github.com/JedWatson/classnames

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Dropdown/Dropdown.jsx
> +    <select value={ value } onChange={ onChange } className={`dropdown ${className}`}>
the same - https://github.com/JedWatson/classnames

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Header/Header.jsx
> +import './Header.scss'
use import scss at the end

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Header/Header.jsx
> +        <header className='header'>
`'` -> `"` for string attributes

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Header/Header.jsx
> +
remove empty lines

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Header/Header.scss
> +    &__title {
add new line before the selector

2021-11-23 20:53 UTC, roman-vabishchevych commented on src/components/Header/Header.scss
> +    &__title, &__filter, &__button {
the same - new line

2021-11-24 16:42 UTC, al-ros commented
@roman-vabishchevych all changes are done

2021-11-24 16:47 UTC, roman-vabishchevych approved these changes

2021-11-24 16:47 UTC, merged